CREATE DATABASE crud_db;
USE crud_db;

CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(100) NOT NULL UNIQUE,
 passw VARCHAR(255) NOT NULL
);
CREATE TABLE products (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nama_produk VARCHAR(100) NOT NULL,
 harga DECIMAL(10,2) NOT NULL,
 stok INT NOT NULL
);

