CREATE TABLE IF NOT EXISTS gambar (
 id INT AUTO_INCREMENT PRIMARY KEY,
 filename VARCHAR(255) NOT NULL,
 filepath VARCHAR(255) NOT NULL,
 thumbpath VARCHAR(255) NOT NULL,
 width INT,
 height INT,
 uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
